// <auto-generated />
namespace HotelsAndUsers.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DeletefieldIdHotel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletefieldIdHotel));
        
        string IMigrationMetadata.Id
        {
            get { return "201806022231574_Delete field IdHotel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
