// <auto-generated />
namespace HotelsAndUsers.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HotelPrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HotelPrice));
        
        string IMigrationMetadata.Id
        {
            get { return "201806111345279_Hotel+Price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
